### ISSUE TITLE
UnitTest crash with Github test

### ISSUE THREAD

**Issue by HomeAutoUser** [fhem/UnitTest#16]
Beim Einbinden von Bsp: https://github.com/RFD-FHEM/RFFHEM/blob/master/t/FHEM/14_SD_UT/09_parseDatat.t crasht FHEM ohne Hinweis im Logfile.

Ist das bekannt oder geht dies prinzipiell nicht?
Bei den alten Testfiles konnte man diese einbinden.

MfG

**Comment by sidey79** [comment]
Kommt darauf an was Du unter einbinden verstehst.

Das ist ja ein perl Kompatibles Testfile. Das hat nichts mit diesem Modul zu tun.

**Comment by sidey79** [comment]
Details zum Test Framework:
https://forum.fhem.de/index.php/topic,111061.msg1053522.html#msg1053522

**Comment by HomeAutoUser** [comment]
`Kommt darauf an was Du unter einbinden verstehst. `

@sidey79 , Ziel sollte sein, alle Tests welche du online durchlaufen lässt, lokal auf dem Rechner mal einzubinden. Das machte ich mit dem oben genannten Fall aber was eben zu einem Crash führt ohne Logfileeinträge.

Leider habe ich mir noch nicht die Mühe gemacht aufgrund von Zeit und fehlenden Mitteln, Zeile für Zeile nacheinander zu durchleuchten wo es genau zu Abbruch führt.

**Comment by sidey79** [comment]
Die Tests laufen auf jedem Linux in dem Perl und FHEM installiert sind.
Die nötigen CPAN Module können bei Bedarf über das CPAN File installiert werden.

Einen Zusammenhang mit diesem Repo gibt es allerdings nicht mehr.
Ist das der einzige Test der fehl schlägt oder trifft das auch auf andere zu?

**Comment by HomeAutoUser** [comment]
Ich werde versuchen das Ganze einzugrenzen aber bisher geht ja absolut garnichts. Siehe https://github.com/fhem/UnitTest/issues/17

**Comment by sidey79** [comment]
Den hier können wir schließen oder?

**Comment by HomeAutoUser** [comment]
Ich denke ja. Ich close ihn.
