### ISSUE TITLE
simple UnitTest crashed FHEM and FHEM restarted

### ISSUE THREAD

**Issue by HomeAutoUser** [fhem/UnitTest#17]
Der definierte Test

```
Internals:
   DEF        sduino_dummy (
{
  my $test = 0;

}
)
   FUUID      60225e5d-f33f-f3b5-ee51-ef74a1b8f1a0fd5d
   NAME       UnitTest
   NR         323
   NTFY_ORDER 50-UnitTest
   STATE      inactive
   TYPE       UnitTest
   name       UnitTest
   targetDevice sduino_dummy
   test_failure 
   test_output 
   todo_output 
   READINGS:
     2021-03-17 11:20:20   state           inactive
     2021-03-17 11:18:30   test_failure    
     2021-03-17 11:18:30   test_output     
     2021-02-09 15:10:30   todo_output     
Attributes:
   disable    1
   room       Unsorted
   verbose    0
```

wir beim starten durch disable 0 versucht auszuführen und lässt FHEM neu starten.

Im Logfile kommt folgende Ausgabe:
```
2021.03.17 11:16:15.004 0: HourCounter Sysmon_CPU_Temp Run.598 first run done countsOverall:395
2021.03.17 11:16:15.132 5: UnitTest/UnitTest_Test_generic: starting test in mainprocess
code sub ($$$) {
    BEGIN {${^WARNING_BITS} = "\x55\x55\x55\x55\x55\x55\x55\x55\x55\x54\x55\x55\x55\x55\x55\x55\x55\x55\x55"}
    use strict;
    my($dev, $loglevel, $text) = @_;
    $dev = $dev->{'NAME'} if defined $dev and ref $dev eq 'HASH';
    if (defined $dev and defined $main::attr{$dev} and defined(my $devlevel = $main::attr{$dev}{'verbose'})) {
        return if $loglevel > $devlevel;
    }
    else {
        return if $loglevel > $main::attr{'global'}{'verbose'};
    }
    return if defined $main::defs{'global'}{'ignoreRegexpObj'} and $text =~ /$main::defs{'global'}{'ignoreRegexpObj'}/;
    my($seconds, $microseconds) = gettimeofday;
    my(@t) = localtime $seconds;
    my $nfile = ResolveDateWildcards($main::attr{'global'}{'logfile'}, @t);
    OpenLogfile $nfile if not $currlogfile or $currlogfile ne $nfile;
    my $tim = sprintf('%04d.%02d.%02d %02d:%02d:%02d', $t[5] + 1900, $t[4] + 1, $t[3], $t[2], $t[1], $t[0]);
    if ($main::attr{'global'}{'mseclog'}) {
        $tim .= sprintf('.%03d', $microseconds / 1000);
    }
    if ($logopened) {
        print LOG "$tim ${loglevel}: $text\n";
    }
    else {
        print "$tim ${loglevel}: $text\n";
    }
    no strict 'refs';
    foreach my $li (keys %main::logInform) {
        if ($main::defs{$li}) {
            &{$main::logInform{$li};}($li, "$tim $loglevel : $text");
        }
        else {
            delete $main::logInform{$li};
        }
    }
    use strict 'refs';
    return undef;
} caused an error: Global symbol "$currlogfile" requires explicit package name (did you forget to declare "my $currlogfile"?) at (eval 440) line 16.
Global symbol "$currlogfile" requires explicit package name (did you forget to declare "my $currlogfile"?) at (eval 440) line 16.
Global symbol "$logopened" requires explicit package name (did you forget to declare "my $logopened"?) at (eval 440) line 21.
BEGIN not safe after errors--compilation aborted at (eval 440) line 27.
2021.03.17 11:16:21.662 1: Including fhem.cfg
```

Intern muss der Fehler vermutlich in dem Prozess der innerhalb der UnitTest_Test_generic Sub hervorgerufen werden.

Kein einziger Test läuft mehr :-(

**Comment by HomeAutoUser** [comment]
Ich habe nun auf meinen @Home System geschaut und hier gehen die gleichen Tests noch. SEHR komisch!
Ich vermute, es fehlt eine Abfrage ob ein Bestandteil auf dem PC installiert ist aber dazu kenne ich die Verarbeitung in der UnitTest_Test_generic Sub zu wenig.

Es zeigt, der Code ist optimierungs fähig.

**Comment by sidey79** [comment]
Hast Du dich an die Installations Anweisung gehalten?

https://github.com/fhem/UnitTest/blob/master/install.md

**Comment by HomeAutoUser** [comment]
Ja denke ich. Es ist zwar schon eine Weile her aber das kann ich nochmal nachstellen morgen und somit dir eine genaue Aussage treffen.

**Comment by HomeAutoUser** [comment]
@sidey79, ja ich habe nun noch einmal die Installations Anweisung verglichen und Step by Step (Requirements for 98_UnitTest.pm) erneut durchgeführt. Der Fehler bleibt gleich.

**Comment by sidey79** [comment]
Ich werde es mir im Debugger ansehen.

Den Fehler habe ich auch schon einmal gehabt, aber wohl vergessen zu dokumentieren

**Comment by HomeAutoUser** [comment]
Erkenntnis @sidey79.
Es muss einen Zusammenhang wie hier https://github.com/fhem/UnitTest/issues/10.

- Sobald ich bei dem Target Device eventlogging auf 1 setze, welches vorher nicht definiert war, geht es auf einmal.
- Ein gesetztes eventlogging 0 ruft ebenso den Fehler hervor

**Comment by sidey79** [comment]
Ich habe den Fehler nachstellen können.
Mal sehen, was ich finde.

**Comment by sidey79** [comment]
@HomeAutoUser 
Ich habe den Fehler nicht so 100% abstellen können.
Das liegt an dclone und der Datenstruktur, welche kopiert wird.

Den Absturz konnte ich aber abfangen. Magst Du es auch mal ausprobieren?

**Comment by HomeAutoUser** [comment]
Ich werde es testen nach dem Wochenende.

**Comment by HomeAutoUser** [comment]
@sidey79

ich habe soeben den Branch https://github.com/fhem/UnitTest/tree/dclone-crashFix
getestet und es kam nicht zum Absturz. Diesen kannst du so übernehmen um dieses Issues abzuschließen.

**Comment by HomeAutoUser** [comment]
@sidey79 ReErinnerung https://github.com/fhem/UnitTest/issues/17#issuecomment-823400443
