### ISSUE TITLE
Idee - Erweiterung Define Modul

### ISSUE THREAD

**Issue by HomeAutoUser** [fhem/UnitTest#2]
Hallo,
mir ging soeben durch den Kopf, man könnte doch die Define überarbeiten um auch den PERL Code direkt von einer Datei zu lesen.

Was haltet Ihr davon?

Vorgehen könnte wie folgt sein,
- prüfen der Argument beim anlegen
- sobald ein ./directory .... /file.txt angegeben ist, so liest man die Datei ein
  - alles was innerhlab der ( ) liegt, nutzt man als Code

... mal als Brainstorming in die Runde geb ;-)

**Comment by sidey79** [comment]
Ich bin mir nicht sicher was das bringt.

Die Definition für den UnitTest muss ja irgendwie angelegt werden. Derzeit wird dann auch gleich der Test mit übergeben.
Was wäre denn besser, wenn das Modul selbst die Datei einliest?
