### ISSUE TITLE
no automatic revised file size

### ISSUE THREAD

**Issue by HomeAutoUser** [fhem/UnitTest#9]
```
Downloading https://raw.githubusercontent.com/RFD-FHEM/UnitTest/master/controls_unittest.txt
UPD FHEM/98_unittest.pm
Got 18561 bytes for FHEM/98_unittest.pm, expected 18166
aborting.
```

with set

`update force https://raw.githubusercontent.com/RFD-FHEM/UnitTest/master/controls_unittest.txt`

**Comment by sidey79** [comment]
@HomeAutoUser 
Der Fehler ist, dass die Update URL auf das archivierte "alte" Repo zeigt.
Ich habe es in der Readme korrigiert. Mit der richtigen URL stimmt auch die Dateigröße

**Comment by HomeAutoUser** [comment]
Perfekt, danke :)
